export const facultyData = [
    { name: "Dr. Sudhir Agarwal", qualification: "Ph.D, MBA, Marketing & Certificate in IITH from IIM Bangalore ", experience: "25+ Years of Corporate Experience with HSBC Bank, IDBI Bank, Citi Bank, Unilever & Haldiram", designation: "Chairman" },
    { name: "Dr. Deepti Agarwal", qualification: "Ph.D, MBA, Marketing & Certificate in IITH from IIM Bangalore ", experience: "22+ Years of Work Experience, Working as a Social Activist in the various NGOs & Corporate Sector", designation: "Director" },
    { name: "Dr. Mridula Sharma", qualification: "Ph.D, MBA ", experience: "18 Years of Academic Experience", designation: "Dean" },
    { name: "Dr. Deepak Gupta", qualification: "Ph.D, M.Com", experience: "25 Years of Work Experience." },
    { name: "Dr. Ashish Sharma", qualification: "Ph.D, MBA, M.Phil", experience: "25 Years of Work Experience in Corporate & Industry" },
    { name: "Dr. Mukul Sharma", qualification: "Ph.D, MBA", experience: "20 Years of Work Experience in Corporate & Industry" },
    { name: "Dr. CA Neha Gupta", qualification: "Ph.D, CA, MBA, M.Com, B.Com", experience: "18 Years of Work Experience in Corporate & Industry" },
    { name: "Prof. Bivash Mukherjee", qualification: "Master in Personnel Management & Industrial Relation", experience: "25 Years of Work Experience in Academics, Corporate, Training & Industry" },
    { name: "Dr. Parul Arora", qualification: "P.hD, MBA (Finance), M.Com (A.B.S.T), NET (Management)", experience: "15 Years of Work Experience in Academics & Corporate" },
    { name: "Dr. Brijesh Awasthi", qualification: "Ph.D", experience: "20 years of Teaching Exp with Top Mgmt" },
    { name: "Dr. Saumya Chobey", qualification: "Ph.D, MBA, M.Com", experience: "15 Years of Work Experience" },
    { name: "Dr. Eti Patni", qualification: "Ph.D, MBA, M.Com", experience: "12 Years of Work Experience" },
    { name: "Dr. Paramanand Sunda", qualification: "Ph.D, M.Com", experience: "10 Years of Work Experience" },
    { name: "Dr. Kailash Saini", qualification: "Ph.D, M.Com", experience: "8 Years of Work Experience" },
    { name: "Dr. Supriya Singhal", qualification: "Ph.D, M.Com, CFA", experience: "10 Years of Work Experience" },
    { name: "Prof. CA Suvidha Chaplot", qualification: "CA (Chartered Accountant), CS (Company Secretary) & MBA from RTU", experience: "15 Years of Work Experience" },
    { name: "Prof. Nutan Mathur", qualification: "MTA (Master of Tourism Administration), M.Com Accounts, B.Com Hons.", experience: "15 Years of Work Experience" },
    { name: "Prof. Ankita Gaur", qualification: "MIB (Master of International Business), MHRM (Master in Human Resource Management), MBA in Marketing & Pursuing Ph.D in Human Resource Management", experience: "14 Years of Corporate, Research & Academic Work Experience" },
    { name: "Prof. Pankaj Singh Rathore", qualification: "MCA from Bangalore University & BCA from Rajasthan University", experience: "18 Years of Academic Experience" },
    { name: "Prof. Anupama Sharma", qualification: "B.Sc. & B.Ed.", experience: "16 Years of Academic Experience" },
    { name: "Mr. Saurabh Counsul", qualification: "M.Com & B.Com", experience: "23 Years of Work Experience" },
    { name: "Prof. Deepshika Bhatia", qualification: "Ph.D Pursuing, MBA (HRM), UGC Net Qualified, B.Com", experience: "12 Years of Work Experience" },
    { name: "Prof. Saurav Nagi", qualification: "MBA from Rajasthan Technical University & BCOM from Rajasthan University", experience: "12 Years of Work Experience" },
    { name: "Prof. Akash Juneja", qualification: "", experience: "10 Years of Work Experience" },
    { name: "Prof. Disha Juneja", qualification: "", experience: "10 Years of Work Experience" },
    { name: "Prof. Disha Sharma", qualification: "", experience: "8 Years of Work Experience" },
    { name: "Prof. Divyansh Saini", qualification: "MCA from Rajasthan University & BCA from Rajasthan University", experience: "6 Years of Work Experience" },
    { name: "Prof. Hemant Gautam", qualification: "MCA & BCA from Rajasthan University", experience: "6 Years of Work Experience" },
    { name: "Prof. Saurabh Bakhliwal", qualification: "", experience: "7 Years of Work Experience" },
    { name: "Prof. Kuldeep Singh Shekhawat", qualification: "MBA from Vivekananda Global University & BA from Rajasthan University", experience: "5 Years of Work Experience" },
    { name: "Prof. Saurabh Goyal", qualification: "MCA from Jaipur National University & BCA from Rajasthan University", experience: "6 Years of Work Experience" },
    { name: "Mr. Jatin Jangid", qualification: "", experience: "IT 6 Years of Work Experience" },
    { name: "Mrs. Paramjeet Kaur", qualification: "", experience: "5 Years of Work Experience" },
    { name: "Prof. Preeti Sharma", qualification: "", experience: "10 Years of Work Experience" },
    { name: "Mr. Sanchita Ray", qualification: "MCA", experience: "5 Years Experience" },
    { name: "Mr. Aashwin Vyas", qualification: "", experience: "2 Years IT Experience" }
];

export const mentorData = [
    { name: "Sh. Khemraj Ji", qualification: "Sr. IAS (1985 Batch), Additional Chief Secretary (Rtd.)", experience: "Govt. of Rajasthan" },
    { name: "Prof. Prabal K. Sen", qualification: "Ex. Professor Area of Economics & Ex. Founding Chairperson EDC", experience: "XLRI Jamshedpur" },
    { name: "Prof. Sanjay Saraswat", qualification: "Managing Director ", experience: "ACE Institute for Education & Languages Pvt. Ltd." },
    { name: "Mr. Vachaspati Purohit", qualification: "Director - I.T.", experience: "HCL - America" },
    { name: "Mr. Sudeep Sharma", qualification: "Principal Partner", experience: "BCG, Chicago - USA" },
    { name: "Mr. Gagan Mittal", qualification: "Executive Director", experience: "Standard Chartered Bank" },
    { name: "Mr. Bhupesh Ahuja", qualification: "Sr. Vice President", experience: "DSP BLACK ROCK (Mutual Fund)" },
    { name: "Mr. Paras M Das", qualification: "Regional Manager - North", experience: "Hughes Communication India Ltd." },
    { name: "Mr. Ashish Jain", qualification: "Sr. Vice Presindent", experience: "AXIS Bank Ltd." },
    { name: "Mr. Jatin Govil", qualification: "Zonal Head (Rajasthan)", experience: "ICICI Bank Ltd." },
    { name: "Mr. Piyush Kumar Saxena", qualification: "Sr. Vice President", experience: "Religare Finvest Ltd." },
    { name: "Mr. Paresh Nankany", qualification: "COO", experience: "GIONEE Mobiles" },
    { name: "Mr. Rohit Mathur", qualification: "Country Head - HR (INDIA)", experience: "Shriram General Insurance Ltd." },
    { name: "Mr. Anand Kushwaha", qualification: "Head - HR (Rajasthan)", experience: "Samasta Microfinance Ltd." },
    { name: "Mr. Anil Sharma", qualification: "Manager - HR", experience: "AIRTEL" },
    { name: "Mr. Ankit Gupta", qualification: "Manager - Operations", experience: "BOSCH" },
    { name: "Mr. Kajal Verma", qualification: "Senior Manager", experience: "Samsung Mobiles" },
    { name: "Mr. Prateek Mitra", qualification: "Area Manager", experience: "ITC Ltd." },
    { name: "Mr. Manish Pareek", qualification: "Regional Team Leader (North Head)", experience: "Ashok Leyland Ltd." },
    { name: "Mr. Saket Mishra", qualification: "Regional Sales Manager", experience: "Induslnd Bank Ltd." },
    { name: "Mr. Rajkamal Tomar", qualification: "Deputy General Manager", experience: "Aditya Birla Ltd." },
    { name: "Mr. Ashish Kumar", qualification: "Deputy Director", experience: "Amity University" },
    { name: "Mr. Paras Rastogi", qualification: "Area Sales Manager", experience: "Bajaj Finserv Ltd." },
    { name: "Mr. Naveen Agrawal", qualification: "Program Manager Deployment", experience: "Bharti Infratel Ltd." },
    { name: "Mr. Rakesh Ranjan", qualification: "Head Supply Chain Management", experience: "Bharti Infratel Ltd." },
    { name: "Mr. Hitesh Desai", qualification: "Zonal Business Manager North Zone", experience: "Novartis India Limited" },
    { name: "Mr. Abhishek Singh", qualification: "Program Manager", experience: "Il&fs Cluster Development Intiative Limited" },
    { name: "Mr. Santosh Kumar Dhal", qualification: "Head - HR", experience: "Shaft Sinkers Mauritius India Project" },
    { name: "Mr. Vikas Kumar", qualification: "Sr. Manager - Sales & Distribution", experience: "Motilal Oswal" },
    { name: "Mr. Aashish Dixit", qualification: "Project Manager", experience: "SASKEN" },
    { name: "Mr. Sandeep Birani", qualification: "Vice President - Sales & Marketing", experience: "SNG Group" },
    { name: "Mr. Amit Kumar", qualification: "Senior Vice President- Projects", experience: "Shristi Infrastructure Dev. Ltd." },
    { name: "Mr. Vikas Tandon", qualification: "Associate Franchise Manager", experience: "PEPSICO" },
    { name: "Mr. Nitesh Kumar", qualification: "Chief Manager- Alternate Channel", experience: "Kotak Life Insurance" },
    { name: "Mr. Lalit Jain", qualification: "Business Head- West", experience: "Spencer's Retail Limited" },
    { name: "Mr. Aakash Modi", qualification: "Country Credit Manager", experience: "Shell India Markets Private Limited" },
    { name: "Sonal Jayaswal", qualification: "Director", experience: "Abhijeet Vision Unlimited" },
    { name: "Mr. Hitender Singh", qualification: "Account Manager", experience: "Hughes Communication India Ltd." },
    { name: "Mr. Satish Sharma", qualification: "North Head - Infra Projects", experience: "HDFC Bank Ltd." },
    { name: "Mr. Vikas Sudrania", qualification: "Wealth Manager", experience: "Citibank India Ltd." },
    { name: "Mr. Varun Mahajan", qualification: "Senior Consultant", experience: "PWC House" },
    { name: "Mr. Rajesh Pareek", qualification: "Senior Manager Trainer", experience: "Genpect" },
    { name: "Mr. Shivaji Kumar Dey", qualification: "Zonal Head", experience: "Edelweiss Asset Management Ltd." },
    { name: "Dr. Deepak Saxena", qualification: "Director Student Advisory Board", experience: "University Of Rajasthan" },
    { name: "Mrs. Aradhana Juneja", qualification: "Head - HR", experience: "Nike Inc. (Toronto)" },
    { name: "Mr. Amit Vashisth", qualification: "Teritory Head", experience: "Tata Motors" },
    { name: "Mr. Aman Bhatia", qualification: "Teritory Head", experience: "Tata Motors" },
    { name: "Mr. Saket Mishra", qualification: "Regional Sales Manager", experience: "Indusind Bank Ltd." },
    { name: "Mr. Ashish Tandon", qualification: "Head - HR (INDIA)", experience: "Finova Capital" },
    { name: "Ms. Shruti Singh", qualification: "Head - HR", experience: "Unitech Wireless Pvt. Ltd." },
    { name: "Mr. Sandeep Samsukha", qualification: "Head Marketing", experience: "Vatika Group" },
    { name: "Mr. Nishant Shekhar", qualification: "Area Manager", experience: "HDFC Bank Ltd." },
    { name: "Mr. Rohit Mogra", qualification: "Head - HR (Rajasthan)", experience: "Deutsche Bank Ltd." },
    { name: "Mr. Neil Judson", qualification: "Brand Manager", experience: "ICICI Bank Ltd" },
    { name: "Mr. Dilip S Rathore", qualification: "National Product Head", experience: "CIPLA Ltd" },
    { name: "Mr. Ashish Dhayal", qualification: "Brand Manager", experience: "Maruti Suzuki India Ltd." },
    { name: "Mr. Abhishek Pathak", qualification: "Area Manager", experience: "Tafe Ltd" },
    { name: "Mr. Raghuveer Rai", qualification: "Head Marketing", experience: "Indus Towers" },
    { name: "Mr. Razib Khan", qualification: "Manager - HR", experience: "Deutsche Bank Ltd." },
    { name: "Mr. Chandra Shekhar Sharma", qualification: "Physics Faculty", experience: "Resonance" },
    { name: "Mr. Ashish Purohit", qualification: "Regional Head", experience: "Reliance Mutual Fund" },
    { name: "Mr. Gajraj Singh Purawat", qualification: "Area Manager", experience: "Anchor Health And Beauty Care Pvt. Ltd." },
];